version: 2
updates:
- package-ecosystem: maven
  directory: "/infra-testing-demo-app"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.testcontainers:testcontainers-bom
    versions:
    - 1.15.1
  - dependency-name: org.codehaus.gmavenplus:gmavenplus-plugin
    versions:
    - 1.12.0
  - dependency-name: com.icegreen:greenmail
    versions:
    - 1.6.1
  - dependency-name: com.icegreen:greenmail-junit5
    versions:
    - 1.6.1
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.18.1
