replicaCount: 1
image:
  repository: sparsick/spring-boot-demo
  tag: latest
  pullPolicy: IfNotPresent
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
resources:
  limits:
    cpu: '0.5'
    memory: 512Mi
  requests:
    cpu: '0.25'
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 30
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 30
nodeSelector: {}
tolerations: []
affinity: {}
spring_boot_demo_chart: {}


